export const industryRoles = [
    { key: 'A&R (Artist & Repertoire) Scout or Manager', text: 'A&R (Artist & Repertoire) Scout or Manager', value: 'A&R (Artist & Repertoire) Scout or Manager' },
    { key: 'Accompanist', text: 'Accompanist', value: 'Accompanist' },
    { key: 'Account Executive (PR, Marketing or Sales)', text: 'Account Executive (PR, Marketing or Sales)', value: 'Account Executive (PR, Marketing or Sales)' },
    { key: 'Account Manager (PR, Marketing or Sales)', text: 'Account Manager (PR, Marketing or Sales)', value: 'Account Manager (PR, Marketing or Sales)' },
    { key: 'Accountant (Qualified)', text: 'Accountant (Qualified)', value: 'Accountant (Qualified)' },
    { key: 'Bookkeeper', text: 'Bookkeeper', value: 'Bookkeeper' },
    { key: 'Administration Assistant', text: 'Administration Assistant', value: 'Administration Assistant' },
    { key: 'Administrator', text: 'Administrator', value: 'Administrator' },
    { key: 'Animateur', text: 'Animateur', value: 'Animateur' },
    { key: 'Arranger', text: 'Arranger', value: 'Arranger' },
    { key: 'Artist Booker (maps into same category as Booking Agent)', text: 'Artist Booker (maps into same category as Booking Agent)', value: 'Artist Booker (maps into same category as Booking Agent)' },
    { key: 'Artist Management Assistant', text: 'Artist Management Assistant', value: 'Artist Management Assistant' },
    { key: 'Artist Manager', text: 'Artist Manager', value: 'Artist Manager' },
    { key: 'Assistant Director, Music Video', text: 'Assistant Director, Music Video', value: 'Assistant Director, Music Video' },
    { key: 'Assistant Editor (Film, TV and Video)', text: 'Assistant Editor (Film, TV and Video)', value: 'Assistant Editor (Film, TV and Video)' },
    { key: 'Assistant Engineer (recording)', text: 'Assistant Engineer (recording)', value: 'Assistant Engineer (recording)' },
    { key: 'Audio Programmer (gaming)', text: 'Audio Programmer (gaming)', value: 'Audio Programmer (gaming)' },
    { key: 'Backing Vocalist', text: 'Backing Vocalist', value: 'Backing Vocalist' },
    { key: 'Backline Technician', text: 'Backline Technician', value: 'Backline Technician' },
    { key: 'Booking Agent (maps into same category as Artist Booker)', text: 'Booking Agent (maps into same category as Artist Booker)', value: 'Booking Agent (maps into same category as Artist Booker)' },
    { key: 'Box Office Assistant', text: 'Box Office Assistant', value: 'Box Office Assistant' },
    { key: 'Box Office Manager', text: 'Box Office Manager', value: 'Box Office Manager' },
    { key: 'Brand / Product Manager (marketing campaigns)', text: 'Brand / Product Manager (marketing campaigns)', value: 'Brand / Product Manager (marketing campaigns)' },
    { key: 'Brand / Product Manager (Assistant)', text: 'Brand / Product Manager (Assistant)', value: 'Brand / Product Manager (Assistant)' },
    { key: 'Business Consultant', text: 'Business Consultant', value: 'Business Consultant' },
    { key: 'Business Development Manager', text: 'Business Development Manager', value: 'Business Development Manager' },
    { key: 'Catalogue Assistant (with publisher, label, etc.)', text: 'Catalogue Assistant (with publisher, label, etc.)', value: 'Catalogue Assistant (with publisher, label, etc.)' },
    { key: 'Catalogue Manager ((with publisher, label, etc.)', text: 'Catalogue Manager ((with publisher, label, etc.)', value: 'Catalogue Manager ((with publisher, label, etc.)' },
    { key: 'Choreographer', text: 'Choreographer', value: 'Choreographer' },
    { key: 'Club Manager', text: 'Club Manager', value: 'Club Manager' },
    { key: 'Composer', text: 'Composer', value: 'Composer' },
    { key: 'Concert Assistant', text: 'Concert Assistant', value: 'Concert Assistant' },
    { key: 'Concert Manager', text: 'Concert Manager', value: 'Concert Manager' },
    { key: 'Conductor', text: 'Conductor', value: 'Conductor' },
    { key: 'Copyist', text: 'Copyist', value: 'Copyist' },
    { key: 'Digital Manager (maps to Social Media manager)', text: 'Digital Manager (maps to Social Media manager)', value: 'Digital Manager (maps to Social Media manager)' },
    { key: 'DJ', text: 'DJ', value: 'DJ' },
    { key: 'Editor (Film and TV Music Editors)', text: 'Editor (Film and TV Music Editors)', value: 'Editor (Film and TV Music Editors)' },
    { key: 'Engineer (audio or sound) (maps to same category as Sound Engineer)', text: 'Engineer (audio or sound) (maps to same category as Sound Engineer)', value: 'Engineer (audio or sound) (maps to same category as Sound Engineer)' },
    { key: 'Lawyer, Entertainment Lawyer', text: 'Lawyer, Entertainment Lawyer', value: 'Lawyer, Entertainment Lawyer' },
    { key: 'Lighting Technician', text: 'Lighting Technician', value: 'Lighting Technician' },
    { key: 'Mastering', text: 'Mastering', value: 'Mastering' },
    { key: 'Mixing Engineer (maps to same category as Sound Mixer)', text: 'Mixing Engineer (maps to same category as Sound Mixer)', value: 'Mixing Engineer (maps to same category as Sound Mixer)' },
    { key: 'Music Technologist', text: 'Music Technologist', value: 'Music Technologist' },
    { key: 'Musician (session)', text: 'Musician (session)', value: 'Musician (session)' },
    { key: 'Orchestra Manager', text: 'Orchestra Manager', value: 'Orchestra Manager' },
    { key: 'Presenter ', text: 'Presenter ', value: 'Presenter ' },
    { key: 'Producer (recorded music)', text: 'Producer (recorded music)', value: 'Producer (recorded music)' },
    { key: 'Promoter', text: 'Promoter', value: 'Promoter' },
    { key: 'Publicist', text: 'Publicist', value: 'Publicist' },
    { key: 'Radio Presenter, Host or DJ', text: 'Radio Presenter, Host or DJ', value: 'Radio Presenter, Host or DJ' },
    { key: 'Radio Tracker', text: 'Radio Tracker', value: 'Radio Tracker' },
    { key: 'Roadie', text: 'Roadie', value: 'Roadie' },
    { key: 'Session Musician', text: 'Session Musician', value: 'Session Musician' },
    { key: 'Singer / Vocalist', text: 'Singer / Vocalist', value: 'Singer / Vocalist' },
    { key: 'Social Media Manager (maps to digital manager) ', text: 'Social Media Manager (maps to digital manager) ', value: 'Social Media Manager (maps to digital manager) ' },
    { key: 'Sound Designer (productions, film, TV, video, gaming)', text: 'Sound Designer (productions, film, TV, video, gaming)', value: 'Sound Designer (productions, film, TV, video, gaming)' },
    { key: 'Sound Engineer (maps to same category as Engineer)', text: 'Sound Engineer (maps to same category as Engineer)', value: 'Sound Engineer (maps to same category as Engineer)' },
    { key: 'Sound Mixer (maps to same category as Mixing Engineer)', text: 'Sound Mixer (maps to same category as Mixing Engineer)', value: 'Sound Mixer (maps to same category as Mixing Engineer)' },
    { key: 'Sound Tech (live sound) (maps to same as Technician)', text: 'Sound Tech (live sound) (maps to same as Technician)', value: 'Sound Tech (live sound) (maps to same as Technician)' },
    { key: 'Studio Manager', text: 'Studio Manager', value: 'Studio Manager' },
    { key: 'Teacher – Instrumental', text: 'Teacher – Instrumental', value: 'Teacher – Instrumental' },
    { key: 'Teacher - vocal', text: 'Teacher - vocal', value: 'Teacher - vocal' },
    { key: 'Technician (sound) (maps to same as Sound Tech)', text: 'Technician (sound) (maps to same as Sound Tech)', value: 'Technician (sound) (maps to same as Sound Tech)' },
    { key: 'Tour Manager', text: 'Tour Manager', value: 'Tour Manager' },
    { key: 'Vocalist', text: 'Vocalist', value: 'Vocalist' }
]
