export const venues = [
  { key: "House of TARG", text: "House of TARG", value: "House of TARG" },
  { key: "Ottawa Chamberfest", text: "Ottawa Chamberfest", value: "Ottawa Chamberfest" },
  { key: "Algonquin Commons Theatre", text: "Algonquin Commons Theatre", value: "Algonquin Commons Theatre" },
  { key: "Capital Music Hall", text: "Capital Music Hall", value: "Capital Music Hall" },
  { key: "Music and Beyond", text: "Music and Beyond", value: "Music and Beyond" },
  { key: "LIVE! on Elgin", text: "LIVE! on Elgin", value: "LIVE! on Elgin" },
  { key: "Rainbow Bistro", text: "Rainbow Bistro", value: "Rainbow Bistro" },
  { key: "1848 (U of Ottawa) ", text: "1848 (U of Ottawa) ", value: "1848 (U of Ottawa) " },
  { key: "Arts Court Theatre ", text: "Arts Court Theatre ", value: "Arts Court Theatre " },
  { key: "Atomic Rooster", text: "Atomic Rooster", value: "Atomic Rooster" },
  { key: "Aux 4 Jeudis", text: "Aux 4 Jeudis", value: "Aux 4 Jeudis" },
  { key: "Avant-Garde Bar", text: "Avant-Garde Bar", value: "Avant-Garde Bar" },
  { key: "Babylon Nightclub", text: "Babylon Nightclub", value: "Babylon Nightclub" },
  { key: "Bar Robo", text: "Bar Robo", value: "Bar Robo" },
  { key: "Barney Danson Theat", text: "Barney Danson Theat", value: "Barney Danson Theat" },
  { key: "Barrymore", text: "Barrymore", value: "Barrymore's" },
  { key: "Bassline Station", text: "Bassline Station", value: "Bassline Station" },
  { key: "Black Sheep Inn", text: "Black Sheep Inn", value: "Black Sheep Inn" },
  { key: "Black Squirrel Books & Cafe", text: "Black Squirrel Books & Cafe", value: "Black Squirrel Books & Cafe" },
  { key: "Bronson Centre", text: "Bronson Centre", value: "Bronson Centre" },
  { key: "Cafe Dekcuf", text: "Cafe Dekcuf", value: "Cafe Dekcuf" },
  { key: "Cafe Nostalgica", text: "Cafe Nostalgica", value: "Cafe Nostalgica" },
  { key: "Canadian Tire Centre", text: "Canadian Tire Centre", value: "Canadian Tire Centre" },
  { key: "Centrepointe Theatre", text: "Centrepointe Theatre", value: "Centrepointe Theatre" },
  { key: "Chateau LaFayette", text: "Chateau LaFayette", value: "Chateau LaFayette" },
  { key: "Club SAW", text: "Club SAW", value: "Club SAW" },
  { key: "Crazy Horse", text: "Crazy Horse", value: "Crazy Horse" },
  { key: "Dominion Tavern", text: "Dominion Tavern", value: "Dominion Tavern" },
  { key: "Elmdale Tavern", text: "Elmdale Tavern", value: "Elmdale Tavern" },
  { key: "Flapjack", text: "Flapjack", value: "Flapjack's" },
  { key: "Gigspace", text: "Gigspace", value: "Gigspace" },
  { key: "Happy Goat Coffee Co", text: "Happy Goat Coffee Co", value: "Happy Goat Coffee Co." },
  { key: "House of Common", text: "House of Common", value: "House of Common" },
  { key: "Irene's Pub", text: "Irene's Pub", value: "Irene's Pub" },
  { key: "Kaffe 1870", text: "Kaffe 1870", value: "Kaffe 1870" },
  { key: "Le Minotaure ", text: "Le Minotaure ", value: "Le Minotaure " },
]

export default venues;